### ISSUE TITLE
Data retrieval

### ISSUE THREAD

**Issue by mattshirvan** [KD0AZT/CSFWinter2021JavaProj#1]
# Dataset for the Machine Learning model
unable to get dataset for model would take up to 3 weeks to scrape data.

## Solutions 
- Find Datasets (very hard I have been looking to no avail)
- New project idea: Sudoku solver, it utilizes an intelligent search algorithm and satisfies the rubric.

**Comment by KD0AZT** [comment]
Sudoku solver sounds like a great idea.

**Comment by mattshirvan** [comment]
Sudoku has replaced ML project!
